# Generated by Django 5.2.1 on 2025-05-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_alter_user_last_name_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQArticle",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField()),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("description", models.TextField()),
                ("category", models.CharField()),
                ("subcategory", models.CharField()),
                ("media", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("item_amount", models.IntegerField()),
                (
                    "chat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.user",
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.item",
                    ),
                ),
            ],
        ),
    ]
