# Generated by Django 5.2.1 on 2025-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "telegram_bot",
            "0004_faqarticle_item_remove_user_id_alter_user_chat_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="media",
            field=models.FileField(upload_to=""),
        ),
    ]
