# Generated by Django 5.2.1 on 2025-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0006_user_delivery_address_alter_item_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="faqarticle",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
